words1 = {"абитуриент": "applicant",
"по крайней мере": "at least",
"награждаться": "to be awarded",
"завершить, выполнить ": "to carry out",
"завершение, окончание": "completion",
"обязательный": "compulsory",
"основная программа": "core curriculum",
"защитить дипломную работу ": "to defend a thesis",
"требование": "demand",
"благодаря, вследствие": "due to",
"образование": "education",
"высшее образование": "higher education",
"среднее образование": "secondary education",
"тщательно разрабатывать ": "to elaborate",
"обеспечивать, гарантировать": "to ensure",
"вечернее обучение": "evening course",
"заочное обучение ": "extramural course",
"последний, заключительный ": "final",
"выпускные экзамены ": "finals",
"рама, рамка": "frame",
"в рамках, пределах ": "in the framework of",
"продолжать ": "to go on",
"вуз ": "higher education establishment",
"гуманитарные науки": "humanities",
"сдать экзамены": "to pass exams",
"начальный ": "primary",
"исследовательская работа": "research paper",
"стипендия": "scholarship",
"наука": "science",
"соб. естественные науки": "sciences",
"похожий, подобный": "similar",
"излагать, формулировать": "to state",
"сдавать конкурсные экзамены ": "to take competitive exams",
"профессиональное училище": "vocational school"}

words2 = {"отменять, упразднять": "to abolish",
"в результате": "as a result",
"власть, администрация": "authorities",
"автономный": "autonomous",
"присуждать что-л.; награждать чем-л. ": "to award",
"быть доступным": "to be available",
"придавать юридическую силу, подтверждать": "to validate",
"двойной": "binary",
"присуждать степень": "to confer a degree",
"уполномочивать, разрешать": "to empower",
"рассматривать": "to examine",
"местный университет": "local university",
"объединение": "merger",
"явный, очевидный": "obvious",
"аспирантура": "postgraduate course",
"обеспечивать": "to provide",
"квалификация ": "qualification",
"подразделить": "to subdivide",
"университетский статус ": "university status"}